version: '3'

services:
  build:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run build

  test:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PG_HOST=db
    command: npm run test${TEST_WATCH_MODE:+:watch}
    depends_on:
      db:
        condition: service_started

  db:
    build:
      context: ./docker-images/postgres-ssl
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_HOST_AUTH_METHOD=md5
